# 工程启动端口
server:
  port:8080

# 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
# Spring属性配置
spring:
  application:
    name: springpersonalproject
  shardingsphere:
    props: #展示修改以后的sql语句
      sql-show: true
    datasource:
      common:
      names: db0
      db0:
        url:
        username:
        password:




